# File Ingestion and Schema Validation

## Task

Read the file using different method

Perform basic Validation of the data

And create a YAML file, and generate summary of file

## Dataset

I found the dataset(2GB) on Kraggle's site. You can also find on here: [Parking_Violations_Issued_-_Fiscal_Year_2017](https://www.kaggle.com/datasets/new-york-city/nyc-parking-tickets?select=Parking_Violations_Issued_-_Fiscal_Year_2017.csv).

*When you download the dataset and want to run this notebook, change the file path to yours.*

## 1. Read the File Using Different Methods

### 1.1 Reading the File with Pandas

In [47]:
import pandas as pd
import time

start_time = time.time()
df_pandas = pd.read_csv("Parking_Violations_Issued_-_Fiscal_Year_2017.csv")
end_time = time.time()

print(f"Pandas read time: {end_time - start_time} seconds")

Pandas read time: 0.31725096702575684 seconds

### 1.2 Reading the File with Dask

In [48]:
import dask.dataframe as dd
import time

start_time = time.time()
df_dask = dd.read_csv("Parking_Violations_Issued_-_Fiscal_Year_2017.csv")
end_time = time.time()

print(f"Dask read time: {end_time - start_time} seconds")

Dask read time: 0.02765488624572754 seconds

### 1.3 Reading the File with Modin

In [49]:
import modin.pandas as mpd
import time

start_time = time.time()
df_modin = mpd.read_csv("Parking_Violations_Issued_-_Fiscal_Year_2017.csv")
end_time = time.time()

print(f"Modin read time: {end_time - start_time} seconds")

Modin read time: 0.5730788707733154 seconds

### Conclusion

Dask has the fastest computational speed.

## 2. Basic Validation

In [50]:
df = df_modin.copy()
df.info()

<class 'modin.pandas.dataframe.DataFrame'>
RangeIndex: 100275 entries, 0 to 100274
Data columns (total 43 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Summons Number                     100275 non-null  int64
 1   Plate ID                           100264 non-null  object
 2   Registration State                 100275 non-null  object
 3   Plate Type                         100275 non-null  object
 4   Issue Date                         100275 non-null  object
 5   Violation Code                     100275 non-null  int64
 6   Vehicle Body Type                  99889 non-null   object
 7   Vehicle Make                       99611 non-null   object
 8   Issuing Agency                     100275 non-null  object
 9   Street Code1                       100275 non-null  int64
 10  Street Code2                       100275 non-null  int64
 11  Street Code3                       100275 non-null  int64
 12  Vehicle Expiration Date            100275 non-null  int64
 13  Violation Location                 81640 non-null   float64
 14  Violation Precinct                 100275 non-null  int64
 15  Issuer Precinct                    100275 non-null  int64
 16  Issuer Code                        100275 non-null  int64
 17  Issuer Command                     81749 non-null   object
 18  Issuer Squad                       81738 non-null   object
 19  Violation Time                     100275 non-null  object
 20  Time First Observed                7916 non-null    object
 21  Violation County                   99929 non-null   object
 22  Violation In Front Of Or Opposite  80847 non-null   object
 23  House Number                       79613 non-null   object
 24  Street Name                        100239 non-null  object
 25  Intersecting Street                30715 non-null   object
 26  Date First Observed                100274 non-null  float64
 27  Law Section                        100274 non-null  float64
 28  Sub Division                       100273 non-null  object
 29  Violation Legal Code               18525 non-null   object
 30  Days Parking In Effect             75627 non-null   object
 31  From Hours In Effect               50046 non-null   object
 32  To Hours In Effect                 50046 non-null   object
 33  Vehicle Color                      98964 non-null   object
 34  Unregistered Vehicle?              10205 non-null   float64
 35  Vehicle Year                       100274 non-null  float64
 36  Meter Number                       16489 non-null   object
 37  Feet From Curb                     100274 non-null  float64
 38  Violation Post Code                71544 non-null   object
 39  Violation Description              90072 non-null   object
 40  No Standing or Stopping Violation  0 non-null       float64
 41  Hydrant Violation                  0 non-null       float64
 42  Double Parking Violation           0 non-null       float64
dtypes: float64(9), int64(9), object(25)
memory usage: 32.9+ MB

In [51]:
# remove special characters and white spaces from column names
df.columns = df.columns.str.replace('[^A-Za-z0-9]+', '', regex=True)
df

,SummonsNumber,PlateID,RegistrationState,PlateType,IssueDate,ViolationCode,VehicleBodyType,VehicleMake,IssuingAgency,StreetCode1,...,VehicleColor,UnregisteredVehicle,VehicleYear,MeterNumber,FeetFromCurb,ViolationPostCode,ViolationDescription,NoStandingorStoppingViolation,HydrantViolation,DoubleParkingViolation
0,5092469481,GZH7067,NY,PAS,07/10/2016,7,SUBN,TOYOT,V,0,...,GY,NaN,2001.0,NaN,0.0,NaN,FAILURE TO STOP AT RED LIGHT,NaN,NaN,NaN
1,5092451658,GZH7067,NY,PAS,07/08/2016,7,SUBN,TOYOT,V,0,...,GY,NaN,2001.0,NaN,0.0,NaN,FAILURE TO STOP AT RED LIGHT,NaN,NaN,NaN
2,4006265037,FZX9232,NY,PAS,08/23/2016,5,SUBN,FORD,V,0,...,BK,NaN,2004.0,NaN,0.0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN
3,8478629828,66623ME,NY,COM,06/14/2017,47,REFG,MITSU,T,10610,...,WH,NaN,2007.0,NaN,0.0,04,47-Double PKG-Midtown,NaN,NaN,NaN
4,7868300310,37033JV,NY,COM,11/21/2016,69,DELV,INTER,T,10510,...,WHITE,NaN,2007.0,NaN,0.0,31 6,69-Failure to Disp Muni Recpt,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100270,8489532126,VLG2913,VA,PAS,04/22/2017,38,SUBN,NISSA,T,40890,...,BLUE,NaN,0.0,NaN,0.0,41,38-Failure to Display Muni Rec,NaN,NaN,NaN
100271,8515301519,14829MJ,NY,COM,02/15/2017,46,VAN,FRUEH,T,24890,...,WHITE,NaN,2016.0,NaN,0.0,25,46B-Double Parking (Com-100Ft),NaN,NaN,NaN
100272,5096996920,XACN55,NJ,PAS,06/10/2017,7,VAN,CHEVR,V,0,...,WHITE,NaN,2004.0,NaN,0.0,NaN,FAILURE TO STOP AT RED LIGHT,NaN,NaN,NaN
100273,8019798468,HES7921,NY,PAS,11/03/2016,21,4DSD,NISSA,T,77050,...,GR,NaN,1998.0,NaN,0.0,03 2,21-No Parking (street clean),NaN,NaN,NaN
100274,5094360383,HCP8100,NY,PAS,11/15/2016,7,4DSD,HONDA,V,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
# Check missing value
df.isna().sum()

SummonsNumber                         0
PlateID                              11
RegistrationState                     0
PlateType                             0
IssueDate                             0
ViolationCode                         0
VehicleBodyType                     386
VehicleMake                         664
IssuingAgency                         0
StreetCode1                           0
StreetCode2                           0
StreetCode3                           0
VehicleExpirationDate                 0
ViolationLocation                 18635
ViolationPrecinct                     0
IssuerPrecinct                        0
IssuerCode                            0
IssuerCommand                     18526
IssuerSquad                       18537
ViolationTime                         0
TimeFirstObserved                 92359
ViolationCounty                     346
ViolationInFrontOfOrOpposite      19428
HouseNumber                       20662
StreetName                           36
IntersectingStreet                69560
DateFirstObserved                     1
LawSection                            1
SubDivision                           2
ViolationLegalCode                81750
DaysParkingInEffect               24648
FromHoursInEffect                 50229
ToHoursInEffect                   50229
VehicleColor                       1311
UnregisteredVehicle               90070
VehicleYear                           1
MeterNumber                       83786
FeetFromCurb                          1
ViolationPostCode                 28731
ViolationDescription              10203
NoStandingorStoppingViolation    100275
HydrantViolation                 100275
DoubleParkingViolation           100275
dtype: int64

In [53]:
# drop_duplicates
df.drop_duplicates()

,SummonsNumber,PlateID,RegistrationState,PlateType,IssueDate,ViolationCode,VehicleBodyType,VehicleMake,IssuingAgency,StreetCode1,...,VehicleColor,UnregisteredVehicle,VehicleYear,MeterNumber,FeetFromCurb,ViolationPostCode,ViolationDescription,NoStandingorStoppingViolation,HydrantViolation,DoubleParkingViolation
0,5092469481,GZH7067,NY,PAS,07/10/2016,7,SUBN,TOYOT,V,0,...,GY,NaN,2001.0,NaN,0.0,NaN,FAILURE TO STOP AT RED LIGHT,NaN,NaN,NaN
1,5092451658,GZH7067,NY,PAS,07/08/2016,7,SUBN,TOYOT,V,0,...,GY,NaN,2001.0,NaN,0.0,NaN,FAILURE TO STOP AT RED LIGHT,NaN,NaN,NaN
2,4006265037,FZX9232,NY,PAS,08/23/2016,5,SUBN,FORD,V,0,...,BK,NaN,2004.0,NaN,0.0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN
3,8478629828,66623ME,NY,COM,06/14/2017,47,REFG,MITSU,T,10610,...,WH,NaN,2007.0,NaN,0.0,04,47-Double PKG-Midtown,NaN,NaN,NaN
4,7868300310,37033JV,NY,COM,11/21/2016,69,DELV,INTER,T,10510,...,WHITE,NaN,2007.0,NaN,0.0,31 6,69-Failure to Disp Muni Recpt,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100270,8489532126,VLG2913,VA,PAS,04/22/2017,38,SUBN,NISSA,T,40890,...,BLUE,NaN,0.0,NaN,0.0,41,38-Failure to Display Muni Rec,NaN,NaN,NaN
100271,8515301519,14829MJ,NY,COM,02/15/2017,46,VAN,FRUEH,T,24890,...,WHITE,NaN,2016.0,NaN,0.0,25,46B-Double Parking (Com-100Ft),NaN,NaN,NaN
100272,5096996920,XACN55,NJ,PAS,06/10/2017,7,VAN,CHEVR,V,0,...,WHITE,NaN,2004.0,NaN,0.0,NaN,FAILURE TO STOP AT RED LIGHT,NaN,NaN,NaN
100273,8019798468,HES7921,NY,PAS,11/03/2016,21,4DSD,NISSA,T,77050,...,GR,NaN,1998.0,NaN,0.0,03 2,21-No Parking (street clean),NaN,NaN,NaN
100274,5094360383,HCP8100,NY,PAS,11/15/2016,7,4DSD,HONDA,V,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 3. Create YAML File

In [54]:
# Get header name
df.columns.tolist()

['SummonsNumber',
 'PlateID',
 'RegistrationState',
 'PlateType',
 'IssueDate',
 'ViolationCode',
 'VehicleBodyType',
 'VehicleMake',
 'IssuingAgency',
 'StreetCode1',
 'StreetCode2',
 'StreetCode3',
 'VehicleExpirationDate',
 'ViolationLocation',
 'ViolationPrecinct',
 'IssuerPrecinct',
 'IssuerCode',
 'IssuerCommand',
 'IssuerSquad',
 'ViolationTime',
 'TimeFirstObserved',
 'ViolationCounty',
 'ViolationInFrontOfOrOpposite',
 'HouseNumber',
 'StreetName',
 'IntersectingStreet',
 'DateFirstObserved',
 'LawSection',
 'SubDivision',
 'ViolationLegalCode',
 'DaysParkingInEffect',
 'FromHoursInEffect',
 'ToHoursInEffect',
 'VehicleColor',
 'UnregisteredVehicle',
 'VehicleYear',
 'MeterNumber',
 'FeetFromCurb',
 'ViolationPostCode',
 'ViolationDescription',
 'NoStandingorStoppingViolation',
 'HydrantViolation',
 'DoubleParkingViolation']

In [55]:
# import shutil
import yaml
import gzip
import os


# Step 1: Read the YAML configuration file
with open("config.yaml") as file:
    config = yaml.safe_load(file)

# Step 2: Validate DataFrame structure against YAML
if list(df.columns) == config["columns"]:
    print("Column validation passed")
else:
    print("Column validation failed. Please check the column names and order.")


# Step 3: Write DataFrame to a gzipped, pipe-separated text file
df_subset = df.iloc[:2000]  # selecting the first 1000 rows
df_subset.to_csv("output_file.csv.gz", sep="|", compression="gzip", index=False)

# Step 4: Create and print a summary of the file
summary = {
    "Total number of rows": len(df),
    "Total number of columns": len(df.columns),
    "File size (bytes)": os.path.getsize("output_file.csv.gz")
}

print("File Summary:", summary)

Column validation passed
File Summary: {'Total number of rows': 100275, 'Total number of columns': 43, 'File size (bytes)': 123475}

UserWarning: `to_csv` is not currently supported by PandasOnDask, defaulting to pandas implementation.