# File Ingestion and Schema Validation

## Task

Read the file using different method

Perform basic Validation of the data

Create a YAML file, and generate summary of file

## Dataset

I found the dataset(2GB) on Kraggle's site. You can also find on here: [Parking_Violations_Issued_-_Fiscal_Year_2017](https://www.kaggle.com/datasets/new-york-city/nyc-parking-tickets?select=Parking_Violations_Issued_-_Fiscal_Year_2017.csv).

*When you download the dataset and want to run this notebook, change the file path to yours.*

## 1. Read the File Using Different Methods

In [1]:
import warnings
warnings.filterwarnings("ignore")

### 1.1 Reading the File with Pandas

In [2]:
import pandas as pd
import time

start_time = time.time()
df_pandas = pd.read_csv("Parking_Violations_Issued_-_Fiscal_Year_2017.csv")
end_time = time.time()

print(f"Pandas read time: {end_time - start_time} seconds")

Pandas read time: 5.016220569610596 seconds

### 1.2 Reading the File with Dask

In [3]:
import dask.dataframe as dd
import time

start_time = time.time()
df_dask = dd.read_csv("Parking_Violations_Issued_-_Fiscal_Year_2017.csv")
end_time = time.time()

print(f"Dask read time: {end_time - start_time} seconds")

Dask read time: 0.0636758804321289 seconds

### 1.3 Reading the File with Modin

In [4]:
import modin.pandas as mpd
import time

start_time = time.time()
df_modin = mpd.read_csv("Parking_Violations_Issued_-_Fiscal_Year_2017.csv")
end_time = time.time()

print(f"Modin read time: {end_time - start_time} seconds")

Modin read time: 14.532036066055298 seconds

### Conclusion

Dask has the fastest computational speed.

## 2. Basic Validation

In [5]:
df = df_modin.copy()
df.info()

<class 'modin.pandas.dataframe.DataFrame'>
RangeIndex: 1666840 entries, 0 to 1666839
Data columns (total 43 columns):
 #   Column                             Non-Null Count    Dtype
---  ------                             --------------    -----
 0   Summons Number                     1666840 non-null  int64
 1   Plate ID                           1666737 non-null  object
 2   Registration State                 1666840 non-null  object
 3   Plate Type                         1666840 non-null  object
 4   Issue Date                         1666840 non-null  object
 5   Violation Code                     1666840 non-null  int64
 6   Vehicle Body Type                  1660421 non-null  object
 7   Vehicle Make                       1655743 non-null  object
 8   Issuing Agency                     1666840 non-null  object
 9   Street Code1                       1666840 non-null  int64
 10  Street Code2                       1666840 non-null  int64
 11  Street Code3                       1666840 non-null  int64
 12  Vehicle Expiration Date            1666840 non-null  int64
 13  Violation Location                 1358388 non-null  float64
 14  Violation Precinct                 1666840 non-null  int64
 15  Issuer Precinct                    1666840 non-null  int64
 16  Issuer Code                        1666840 non-null  int64
 17  Issuer Command                     1359823 non-null  object
 18  Issuer Squad                       1359685 non-null  object
 19  Violation Time                     1666833 non-null  object
 20  Time First Observed                130609 non-null   object
 21  Violation County                   1661002 non-null  object
 22  Violation In Front Of Or Opposite  1345154 non-null  object
 23  House Number                       1325360 non-null  object
 24  Street Name                        1666262 non-null  object
 25  Intersecting Street                510413 non-null   object
 26  Date First Observed                1666840 non-null  int64
 27  Law Section                        1666840 non-null  int64
 28  Sub Division                       1666723 non-null  object
 29  Violation Legal Code               307023 non-null   object
 30  Days Parking In Effect             1258592 non-null  object
 31  From Hours In Effect               828684 non-null   object
 32  To Hours In Effect                 828684 non-null   object
 33  Vehicle Color                      1644379 non-null  object
 34  Unregistered Vehicle?              168778 non-null   float64
 35  Vehicle Year                       1666840 non-null  int64
 36  Meter Number                       271353 non-null   object
 37  Feet From Curb                     1666840 non-null  int64
 38  Violation Post Code                1191050 non-null  object
 39  Violation Description              1498076 non-null  object
 40  No Standing or Stopping Violation  0 non-null        float64
 41  Hydrant Violation                  0 non-null        float64
 42  Double Parking Violation           0 non-null        float64
dtypes: float64(5), int64(13), object(25)
memory usage: 546.8+ MB

In [6]:
# remove special characters and white spaces from column names
df.columns = df.columns.str.replace('[^A-Za-z0-9]+', '', regex=True)
df

,SummonsNumber,PlateID,RegistrationState,PlateType,IssueDate,ViolationCode,VehicleBodyType,VehicleMake,IssuingAgency,StreetCode1,...,VehicleColor,UnregisteredVehicle,VehicleYear,MeterNumber,FeetFromCurb,ViolationPostCode,ViolationDescription,NoStandingorStoppingViolation,HydrantViolation,DoubleParkingViolation
0,5092469481,GZH7067,NY,PAS,07/10/2016,7,SUBN,TOYOT,V,0,...,GY,NaN,2001,NaN,0,NaN,FAILURE TO STOP AT RED LIGHT,NaN,NaN,NaN
1,5092451658,GZH7067,NY,PAS,07/08/2016,7,SUBN,TOYOT,V,0,...,GY,NaN,2001,NaN,0,NaN,FAILURE TO STOP AT RED LIGHT,NaN,NaN,NaN
2,4006265037,FZX9232,NY,PAS,08/23/2016,5,SUBN,FORD,V,0,...,BK,NaN,2004,NaN,0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN
3,8478629828,66623ME,NY,COM,06/14/2017,47,REFG,MITSU,T,10610,...,WH,NaN,2007,NaN,0,04,47-Double PKG-Midtown,NaN,NaN,NaN
4,7868300310,37033JV,NY,COM,11/21/2016,69,DELV,INTER,T,10510,...,WHITE,NaN,2007,NaN,0,31 6,69-Failure to Disp Muni Recpt,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1666835,8470923894,HCR6834,NY,PAS,01/13/2017,21,4DSD,NISSA,T,44620,...,BK,NaN,2015,NaN,0,06,21-No Parking (street clean),NaN,NaN,NaN
1666836,8169534197,FSV9163,NY,PAS,07/02/2016,37,4DSD,HYUND,T,36130,...,TN,NaN,2012,306-3174,0,34 3,37-Expired Muni Meter,NaN,NaN,NaN
1666837,7170228658,GFD6973,NY,PAS,02/18/2017,70,4DSD,KIA,T,22550,...,GY,NaN,2013,NaN,0,C-AM,70A-Reg. Sticker Expired (NYS),NaN,NaN,NaN
1666838,1411673645,G83BMR,NJ,PAS,09/11/2016,67,SDN,TOYOT,P,73480,...,BLACK,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
1666839,8263626201,GTF5615,NY,PAS,11/23/2016,14,SUBN,ACURA,T,75970,...,GY,NaN,2011,NaN,0,NaN,NaN,NaN,NaN,NaN

In [7]:
# Check missing value
df.isna().sum()

SummonsNumber                          0
PlateID                              103
RegistrationState                      0
PlateType                              0
IssueDate                              0
ViolationCode                          0
VehicleBodyType                     6419
VehicleMake                        11097
IssuingAgency                          0
StreetCode1                            0
StreetCode2                            0
StreetCode3                            0
VehicleExpirationDate                  0
ViolationLocation                 308452
ViolationPrecinct                      0
IssuerPrecinct                         0
IssuerCode                             0
IssuerCommand                     307017
IssuerSquad                       307155
ViolationTime                          7
TimeFirstObserved                1536231
ViolationCounty                     5838
ViolationInFrontOfOrOpposite      321686
HouseNumber                       341480
StreetName                           578
IntersectingStreet               1156427
DateFirstObserved                      0
LawSection                             0
SubDivision                          117
ViolationLegalCode               1359817
DaysParkingInEffect               408248
FromHoursInEffect                 838156
ToHoursInEffect                   838156
VehicleColor                       22461
UnregisteredVehicle              1498062
VehicleYear                            0
MeterNumber                      1395487
FeetFromCurb                           0
ViolationPostCode                 475790
ViolationDescription              168764
NoStandingorStoppingViolation    1666840
HydrantViolation                 1666840
DoubleParkingViolation           1666840
dtype: int64

## 3. Create YAML File

In [8]:
# Get header name
df.columns.tolist()

['SummonsNumber',
 'PlateID',
 'RegistrationState',
 'PlateType',
 'IssueDate',
 'ViolationCode',
 'VehicleBodyType',
 'VehicleMake',
 'IssuingAgency',
 'StreetCode1',
 'StreetCode2',
 'StreetCode3',
 'VehicleExpirationDate',
 'ViolationLocation',
 'ViolationPrecinct',
 'IssuerPrecinct',
 'IssuerCode',
 'IssuerCommand',
 'IssuerSquad',
 'ViolationTime',
 'TimeFirstObserved',
 'ViolationCounty',
 'ViolationInFrontOfOrOpposite',
 'HouseNumber',
 'StreetName',
 'IntersectingStreet',
 'DateFirstObserved',
 'LawSection',
 'SubDivision',
 'ViolationLegalCode',
 'DaysParkingInEffect',
 'FromHoursInEffect',
 'ToHoursInEffect',
 'VehicleColor',
 'UnregisteredVehicle',
 'VehicleYear',
 'MeterNumber',
 'FeetFromCurb',
 'ViolationPostCode',
 'ViolationDescription',
 'NoStandingorStoppingViolation',
 'HydrantViolation',
 'DoubleParkingViolation']

In [9]:
# import shutil
import yaml
import gzip
import os


# Step 1: Read the YAML configuration file
with open("config.yaml") as file:
    config = yaml.safe_load(file)

# Step 2: Validate DataFrame structure against YAML
if list(df.columns) == config["columns"]:
    print("Column validation passed")
else:
    print("Column validation failed. Please check the column names and order.")

# Step 3: Write DataFrame to a gzipped, pipe-separated text file
df_subset = df.iloc[:2000]  # selecting the first 1000 rows
df_subset.to_csv("output_file.csv.gz", sep="|", compression="gzip", index=False)

# Step 4: Create and print a summary of the file
summary = {
    "Total number of rows": len(df),
    "Total number of columns": len(df.columns),
    "File size (bytes)": os.path.getsize("output_file.csv.gz")
}

print("File Summary:", summary)

Column validation passed
File Summary: {'Total number of rows': 1666840, 'Total number of columns': 43, 'File size (bytes)': 123475}